export { campus } from "./campus.ts";
export { departments } from "./departments.ts";
export { majors } from "./majors.ts";
export { users, usersRelations } from "./users.ts";
export { sessions, sessionsRelations } from "./sessions.ts";
export { accounts, accountsRelations } from "./accounts.ts";
export { verifications } from "./verifications.ts";
export { terms } from "./terms.ts";
export { applications, applicationsRelations } from "./applications.ts";
export { grades, gradesRelations } from "./grades.ts";
export { documents, documentsRelations } from "./documents.ts";
export { applicationDrafts, applicationDraftsRelations } from "./application-drafts.ts";
